rossumai/university

.github/renovate.json5
renovate.json

Inspired by: https://github.com/adeira/universe/blob/1199fd501661081eab49e4be22e62bf8a3186bf2/.github/renovate.json5

Renovate: update configuration

---

docs/extensions/coupa/import-configuration.md

- Lookup values
- UOMS (Units of measurements)

2 new configuration examples

---

docs/extensions/business-rules-validation/expression-engine.md

BRV configuration examples mistakes fixed.

sergey-brv-mistake-correction

---

docs/learn/master-data-hub/configuration-examples.md

To be alphabetically sorted and follow the same example convention.

Data matching: update config examples

---

docs/learn/line-items-grouping/configuration-examples.md
docs/learn/line-items-grouping/index.md
tests/pages.spec.js

To be aligned with the service name/URL

Line items grouping: rename

---

docs/learn/emails/auto-rejections.md
docs/learn/emails/index.md

Prettier + Markdown changes for easier reading.

Emails: improve formatting

---

docs/learn/ai-learning/index.md
src/pages/index.js
tests/pages.spec.js

Adding a page dedicated to AI training best practices. The first chapter is about queues and when to consider splitting them.

AI-Training-Best-Practices

---

docs/learn/netsuite/import-configuration.md

This will allow us to scale this section better and add more information there (such as necessary permissions in NetSuite).

NS: refactor individual import examples

---

docs/learn/ai-learning/index.md

- Slight changes in information order
- More information is added

Ai training updates3

---

docs/learn/_rossum_only.md

Example usage:
```
import RossumOnly from '../_rossum_only.md';
<RossumOnly url="https://rossumai.atlassian.net/l/cp/Mzc6njHG" />
```

Create `RossumOnly` component for restricted access links

---

docs/learn/data-value-extractor/index.md
docs/learn/export-pipeline/index.md
docs/learn/rest-api-export/configuration-examples.md

New mega documentation - draft

---

docs/learn/master-data-hub/configuration-examples.md

Add tips to VAT ID checker against external API

Update VAT ID checker against external API

---

docs/learn/export-pipeline/custom-format-templating.md
docs/learn/export-pipeline/data-value-extractor.md
docs/learn/export-pipeline/export-evaluator.md
docs/learn/export-pipeline/index.md
docs/learn/export-pipeline/rest-api-export.md

Re-shuffle some parts and remove the unfinished ones (or references to nowhere).

Export pipelines: improve docs

---

docs/learn/ai-learning/index.md

Added new FAQ item "How can I correct inaccurate annotations to improve AI predictions?"

AI-updates-3

---

docs/learn/export-pipeline/custom-format-templating-purge.md
docs/learn/export-pipeline/custom-format-templating.md
docs/learn/export-pipeline/data-value-extractor.md

- Minor changes (missing Schema in the install) and some installation examples added.
- My first review of the process after first happy path deploy under my account

Minor changes to Export pipelines

---

docs/learn/email-body-converter/index.md

adding email body converter to university + slight changes and fix of grammar errors

Email body converter

---

docs/learn/rossum-formulas/formula-fields.md

Added a common description of FF + best practicies + example of date validation on FF level

Formula fields update

---

docs/learn/rossum-formulas/formula-fields.md

Plus some minor edits to be aligned with https://rossum.university/docs/docusaurus/best-practices-for-content

FF: run prettier

---

docs/learn/integration-patterns/index.md

Small wording correction to maintain consistency.

integration-patterns-correction

---

docs/learn/coupa/import-configuration.md

Added a basic explanation to import-configuration.md for easier understanding.

Minor update of Coupa integration

---

docs/learn/coupa/import-configuration.md

Added a missing link for Coupa import for US.

Missing link for import Coupa US region

---

docs/learn/ai-learning/index.md

Added information about ambiguous dates in the AI section.

qna-about-dates

---

docs/learn/export-pipeline/data-value-extractor.md

Updated documentation for the Data Value Extractor. New examples and parameters definition.

Data Value Extractor Update.

---

docs/learn/export-pipeline/data-value-extractor.md
docs/learn/export-pipeline/rest-api-export.md

- Corrected mistake in data value extractor regarding condition definition.
- Improved documentation of rest api connector (general structure, original file, stored header info, status code resolver).

Export pipelines documentation improvements.
